### ISSUE TITLE
Change the logo

### ISSUE THREAD

**Issue by timokonkwo** [timokonkwo/techtalk#10]
The logo on the nav is looking weird.

It needs improvement.

**Comment by boularbahsmail** [comment]
I uploaded a better-looking logo (Light-Logo & Dark-Logo), You may want to take a look at it.

**Comment by timokonkwo** [comment]
Thank you for your wonderful work. 
The logo is beautiful
We will look forward to using your logo concept specifically for tech talk. Please do replace the **SoftAmplify Technologies** in the logo text with **tech talk** and submit a PR.

**Comment by boularbahsmail** [comment]
Sure, I'll be happy to, I'll make the changes and I'll submit a PR.
