### ISSUE TITLE
Website changes.

### ISSUE THREAD

**Issue by jamextech1** [timokonkwo/techtalk#15]
The Website is Epic, But i think the " I'm in " btn on the Register Now should be changed to " Submit ", 

Also The Glimpse of our past event section should be changed to be in form of a sliding carousel, that'll make it more professional, and even contain more past speakers profiles from the past Tech Talk.

Finally for Now 😁, That, Who's Speaking Section, i think displaying the picture of the speaker we already had meeting with looks somehow not professional, i think it should be the speaker of the coming, Tech Talk, That will make the section more interesting, with that " i can't " feeling it'll put on the website visitors, 
Thank you!!

**Comment by timokonkwo** [comment]
Thanks for spotting out these issues.

As we proceed, someone might take it up and fix it. If you can, you can also contribute to it.

**Comment by jamextech1** [comment]
Okay Sir, No Problem.
